Repository DivyeshPatel6901/robocodeFall2024, pull requests merged in 2024-11, with the labels that each got.

#13 Refactored Clone in WindowPositionManager.java (line 63 & 72)
  robocode.ui/src/main/java/net/sf/robocode/ui/dialog/WindowPositionManager.java
Labels: group-14, remove-software-clone

#14 Refactor getReadableDirectory() and getWritableDirectory() to eliminate Code Duplication.
  robocode.repository/src/main/java/net/sf/robocode/repository/items/RobotItem.java
Labels: group-14, remove-software-clone

#16 Issue1-Remove Code Duplication in openHandlers and closeHandlers Methods in RootHandler.java(line 39 and line 46) Issue2- Refactor JarExtractor to remove code duplication and correctly handle directory creation(line 50 and line 71)
  robocode.repository/src/main/java/net/sf/robocode/repository/packager/JarExtractor.java
  robocode.repository/src/main/java/net/sf/robocode/repository/root/handlers/RootHandler.java
Labels: group-14, remove-software-clone

#15 Issue: Code Duplication (3-line) in file JarCreator.java at lines 158…
  robocode.repository/src/main/java/net/sf/robocode/repository/packager/JarCreator.java
Labels: group-14, remove-software-clone

#18 sri--case-study2
  robocode.tests.robots/src/main/java/tested/robots/RadarTurnRateAndSetAdjust.java
Labels: documentation, group-14

#19 Fixed SSRF vulnerability in readJarStream method by Validating URL Input
  robocode.repository/src/main/java/net/sf/robocode/repository/root/JarRoot.java
Labels: group-14, remove-software-vulnerability

#20 Fixed MET03 vulnerability in checkAccess method
  robocode.host/src/main/java/net/sf/robocode/host/security/RobocodeSecurityManager.java
Labels: group-14, remove-software-vulnerability
